version: '3'

services:
  php-fpm:
    image: php:7.4.2-fpm
    container_name: demo-php-fpm
    volumes:
      - ./:/var/www/demo
    networks:
      - backend

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    container_name: demo-nginx
    volumes:
      - ./:/var/www/demo
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    expose:
      - "8080"
    networks:
      backend:
        ipv4_address: 172.21.0.4

  varnish:
    image: varnish:6
    container_name: demo-varnish
    command: "-p thread_pools=4 -p thread_pool_min=4000 -p thread_pool_max=4000"
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
      - workdir:/var/lib/varnish
    ports:
      - "8081:80"
    networks:
      - backend

  locust-fast:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile_fast.py -H http://master:8089

  locust-slow:
    image: locustio/locust
    ports:
     - "8090:8090"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile_slow.py -H http://master:8089 -P 8090

volumes:
  workdir:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  backend:
    driver: bridge 
    driver_opts:
      com.docker.network.driver.mtu: 1450
    ipam:
      config:
        - subnet: 172.21.0.0/16
